magis_sawrapped/dashboard/urls.py
from django.urls import path
from .views import (dashboard, GradeListView, GradeUpdateView,
                    GradeDeleteView, GradeCreateView)

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('grades/', GradeListView.as_view(), name='grades-list'),
    path('grades/<int:pk>/edit/', GradeUpdateView.as_view(), name='grade-update'),
    path('grades/<int:pk>/delete/', GradeDeleteView.as_view(), name='grade-delete'),
    path('grades/add/', GradeCreateView.as_view(), name='grade-create'),
]

app_name = "dashboard"

magis_sawrapped/login/urls.py
from django.urls import path
from .views import (user_login, user_register)

urlpatterns = [
    path('register/', user_register, name='register'),
    path('', user_login, name='login'),
]

appname = "login"

magis_sawrapped/magis_sawrapped/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('', include('login.urls')),
    path('schedo/', include('schedo.urls')),
] 

magis_sawrapped/schedo/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', UScheduleHTMxTableView.as_view(), name='index'),
    path('<int:pk>/details/', UserTableDetailView.as_view(), name='userTable-details'),
    path('add/', UserTableCreateView.as_view(), name='userTable-create'),
    path('<int:pk>/edit/', UserTableUpdateView.as_view(), name='userTable-update'),
    # path('index_card', index_card_view, name='index_card'),
]

app_name = "schedo"

magis_sawrapped/dashboard/models.py
from django.db import models
from django.urls import reverse
from schedo.models import SchoolYear, Subject
from django.contrib.auth.models import User


class Grade(models.Model):
    
    username = models.ForeignKey(
        User, on_delete=models.CASCADE, default='', limit_choices_to={'is_staff': False}, null=True)
    semester = models.ForeignKey(
        SchoolYear, on_delete=models.CASCADE, default='')
    subject = models.ForeignKey(
        Subject, on_delete=models.CASCADE, default='')
    GRADE_CHOICES = (
        ("A", "A"),
        ("B+", "B+"),
        ("B", "B"),
        ("C+", "C+"),
        ("C", "C"),
        ("D", "D"),
        ("F", "F"),
        ("S", "S"),
        ("WP", "WP"),
    )
    grade = models.CharField(max_length=2, choices=GRADE_CHOICES, default='A')
    
    class Meta:
        constraints = [models.UniqueConstraint(
            fields=['username', 'semester', 'subject'],
            name='sem_and_sub__uniq')]
        ordering = ['username', '-semester', 'grade']

    def __str__(self):
        return '{}'.format(self.grade)

    def get_absolute_url(self):
        return reverse('dashboard:grades-list')

magis_sawrapped/dashboard/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.contrib import messages

from .models import Grade
from .grades import get_grades, Grades

import json

@login_required
def dashboard(request):
    grades = Grades()
    
    df = get_grades()
    cumulative_qpi = grades.cumulative_qpi()
    latest_qpi = grades.latest_qpi()
    dean_list = grades.dean_list()

    qpi_by_semester = grades.qpi_by_semester()
    semester = json.dumps(qpi_by_semester['Semester'].tolist())
    qpi = json.dumps(qpi_by_semester['QPI'].tolist())

    letter_frequency = grades.letter_frequency()
    final_grade = json.dumps(letter_frequency['Final Grade'].tolist())
    subject_code = json.dumps(letter_frequency['Subject Code'].tolist())

    context = {'df': df,
               'cumulative_qpi': cumulative_qpi,
               'latest_qpi': latest_qpi,
               'dean_list': dean_list,
               'semester': semester,
               'qpi': qpi,
               'final_grade': final_grade,
               'subject_code': subject_code}

    # Pass user grades to the template
    context = {'user_grades': grades}
    return render(request, 'dashboard/dashboard.html', context)

    

class GradeListView(ListView):
    model = Grade
    template_name = 'dashboard/view_grades.html'
    def get_queryset(self):
        # Get the default queryset
        queryset = super().get_queryset()
        # Filter the queryset based on the currently logged-in user's username
        filtered_queryset = queryset.filter(username=self.request.user)
        return filtered_queryset


class GradeUpdateView(UpdateView):
    model = Grade
    fields = '__all__'
    template_name = 'dashboard/edit_grade.html'


class GradeDeleteView(DeleteView):
    model = Grade
    success_url = "/grades/"
    template_name = 'dashboard/delete_grade.html'


class GradeCreateView(LoginRequiredMixin, CreateView):
    model = Grade
    fields = ['semester', 'subject', 'grade']
    template_name = 'dashboard/add_grade.html'
    success_url = reverse_lazy('dashboard:grades-list')

    def form_valid(self, form):
        current_user = self.request.user
        user_instance = User.objects.get(username=current_user.username)
        form.instance.username = user_instance
        try:
            return super().form_valid(form)
        except IntegrityError:
            messages.error(self.request, 'Grade entry already exists for this semester and subject.')
            return self.render_to_response(self.get_context_data(form=form))

magis_sawrapped/dashboard/templates/dashboard/add_grade.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Add New Grade{% endblock %}

{% block header %}<h1>Add New Grade</h1>{% endblock %}

{% block content %}
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="submitB" type="submit" value="Add Grade">
</form>

{% endblock %}

magis_sawrapped/dashboard/templates/dashboard/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Dashboard
{% endblock %}

{% block headImports %}

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

{% endblock %}

{% block content %}
<body style = 
    "background: linear-gradient(180deg,  #172554 0%, #1E40AF 100%);
    color: #FFF;
    font-family: Inter;
    ">
<div class = "container vh-100">
    <div class = "row" style = "gap: 1%; height: 95%;">
        <div class = "col-7" style = "
            display: flex;
            flex-direction: column;
            justify-content: space-between;">
            <div class="row">
                <div class="col"
                style = "
                display: flex;
                padding: 30px 32px;
                justify-content: space-between;
                align-items: flex-end;
                border-radius: 45px;
                border: 2px solid #EFF6FF;
                box-shadow: 0px 4px 4px 0px rgba(0, 0, 0, 0.25);
                backdrop-filter: blur(36.45000076293945px);">
                    <h1 style = "color: #fff;
                    font-size: 72px;
                    font-style: normal;
                    font-weight: 500;
                    line-height: 90px;
                    letter-spacing: -1.44px;">
                        Welcome, <br> <b>{{ user.username }}!</b>
                    </h1>
                    <img src="{% static 'Clipboard.png' %}" style = "width: 133px;
                    height: 165px;">
                </div>
            </div>
            <div class = "row" >
                <div class = "col-6"
                    style = "
                    display: flex;
                    padding: 26px 26px;
                    justify-content: space-between;
                    align-items: flex-end;
                    border-radius: 45px;
                    border: 6px solid #121471;
                    box-shadow: 0px 4px 4px 0px rgba(0, 0, 0, 0.25);
                    backdrop-filter: blur(36.45000076293945px);">
                    <img src = "{% static 'Calendar.png' %}" style = "width: 120px;">
                    <a href ="{% url 'schedo:index' %}"
                    style = "
                    color: #FFF;
                    text-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
                    font-size: 44px;
                    font-style: normal;
                    font-weight: 700;
                    text-decoration: none;
                    line-height: normal;">Schedo</a>
                </div>
                <div class = "col-6"
                    style = "
                    display: flex;
                    padding: 26px 26px;
                    justify-content: space-between;
                    align-items: flex-end;
                    border-radius: 45px;
                    border: 6px solid #121471;
                    box-shadow: 0px 4px 4px 0px rgba(0, 0, 0, 0.25);
                    backdrop-filter: blur(36.45000076293945px);">
                    <img src = "{% static 'VizProf.png' %}" style = "width: 120px; height: 120px;">
                    <a href = "#" 
                    style = "
                    color: #FFF;
                    text-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
                    font-size: 44px;
                    font-style: normal;
                    font-weight: 700;
                    text-decoration: none;
                    line-height: normal;">
                        VizProf
                    </a>
                </div>
            </div>
        </div>
        <div class = "col-4"
        style = "display: flex;
            width: 497px;
            height: 600px;
            gap: 2%;
            flex-direction: column;
            justify-content: space-between;
            align-items: flex-start;">
            <div class ="row" style = "gap: 2%;">
                <div class = "col" style = "
                    padding: 30px 32px;
                    border-radius: 45px;
                    border: 2px solid #EFF6FF;
                    box-shadow: 0px 4px 4px 0px rgba(0, 0, 0, 0.25);
                    backdrop-filter: blur(36.45000076293945px);">
                    <div class="dean-list">
                        <h3>Dean's Lister Award</h3>
                        <p>{{ dean_list }}</p>
                    </div>
                    
                    {% for s in semester %}
                    {{ s }}
                    {% endfor %}
                    
                    {% for q in qpi %}
                    {{ q }}
                    {% endfor %}
                    
                </div>
                <div class = "col" style = "gap: 2%;">
                    <div class = "row"
                        style = "
                        padding: 30px 32px;
                        border-radius: 45px;
                        border: 2px solid #EFF6FF;
                        box-shadow: 0px 4px 4px 0px rgba(0, 0, 0, 0.25);
                        backdrop-filter: blur(36.45000076293945px);">
                        <div class="cumulative-qpi">
                            <h3>Cumulative QPI</h3>
                            <p>{{ cumulative_qpi }}</p>
                        </div>
                    </div>
                    <div class = "row"
                        style = "
                        margin-top: 2%;
                        padding: 30px 30px;
                        border-radius: 45px;
                        border: 2px solid #EFF6FF;
                        box-shadow: 0px 4px 4px 0px rgba(0, 0, 0, 0.25);
                        backdrop-filter: blur(36.45000076293945px);">
                        <!-- <div class="latest-qpi">
                            <h3>Latest Semestral QPI</h3>
                            <p>{{ latest_qpi }}</p>
                        </div> -->
                        <h4>QPI by Semester</h4>

                        <canvas id="qpiBySem">
                        </canvas>

                        <script>
                            let semester = JSON.parse('{{ semester|safe }}');
                            let qpi = JSON.parse('{{ qpi|safe }}');

                            // Creating line chart
                            let a = document.getElementById('qpiBySem').getContext('2d');
                            let qpiBySem = new Chart(a, {
                                type: 'line',
                                data: {
                                    labels: semester,
                                    datasets: [
                                        {
                                            label: 'QPI',
                                            data: qpi,
                                            fill: false,
                                            borderColor: 'rgb(75, 192, 192)',
                                            tension: 0.1
                                        },
                                    ]
                                },
                            });
                        </script>
                    </div>
                </div>
            </div>
            <div class = "row" style = "align-self: stretch;">
                <!-- <div class="grades-table table" style = "
                    padding: 31px 36px;
                    border-radius: 45px;
                    border: 2px solid #EFF6FF;
                    box-shadow: 0px 4px 4px 0px rgba(0, 0, 0, 0.25);
                    backdrop-filter: blur(36.45000076293945px);
                    align-self: stretch;">
                    <table>
                
                        <tr>
                            {% for column in df.columns %}
                            <th>{{ column }}</th>
                            {% endfor %}
                        </tr>
                
                        {% for row in df.values %}
                        <tr>
                            {% for value in row %}
                            <td>{{ value }}</td>
                            {% endfor %}
                        </tr>
                        {% endfor %}
                
                    </table> -->
                    <div style = "
                        display:flex;
                        flex-direction: row;
                        padding: 30px 32px;
                        border-radius: 45px;
                        border: 2px solid #EFF6FF;
                        box-shadow: 0px 4px 4px 0px rgba(0, 0, 0, 0.25);
                        backdrop-filter: blur(36.45000076293945px);
                        align-self: stretch;">

                        <h3 style = "align-self: center;">Cumulative Letter Grade Frequency</h3>
                        <div style = "width:fit-content; height: fit-content;">
                        
                        <canvas id="letterFreq">
                        </canvas>

                        <script>
                            let final_grade = JSON.parse('{{ final_grade|safe }}');
                            let subject_code = JSON.parse('{{ subject_code|safe }}');

                            // Creating line chart
                            let b = document.getElementById('letterFreq').getContext('2d');
                            let letterFreq = new Chart(b, {
                                type: 'doughnut',
                                data: {
                                    labels: final_grade,
                                    datasets: [
                                        {
                                            label: 'Subject Code',
                                            data: subject_code,
                                            backgroundColor: [
                                                'rgb(255, 99, 132)',
                                                'rgb(54, 162, 235)',
                                                'rgb(255, 205, 86)'
                                            ],
                                            hoverOffset: 4
                                        },
                                    ]
                                },
                            });
                        </script>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
{% endblock %}

magis_sawrapped/dashboard/templates/dashboard/delete_grade.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Delete Grade in {{ object.subject.subject_code }}{% endblock %}

{% block header %} <h1> Delete Grade </h1> {% endblock %}

{% block content %}

<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete your grade in <strong>{{ object.subject.subject_code }}</strong>?</p>
    <input type="submit" value="Confirm">
</form>
<a href="{% url 'dashboard:grades-list' %}"><button>Cancel</button></a>

{% endblock %}

magis_sawrapped/dashboard/templates/dashboard/edit_grade.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Edit Grade in {{ object.subject.subject_code }}{% endblock %}

{% block header %} <h1> Edit Grade </h1> {% endblock %}

{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save Changes">
</form>

{% endblock %}

magis_sawrapped/dashboard/templates/dashboard/view_grades.html
{% extends 'base.html' %}
{% load static %}

{% block title %} My Grades {% endblock %}

{% block header %}
<h1>View Grades</h1>
{% endblock %}

{% block content %}

<p><a href="{% url 'dashboard:grade-create' %}">Add New Grade</a></p>

<table>

    <tr>
        <th>School Year</th>
        <th>Sem</th>
        <th>Subject Code</th>
        <th>Course Title</th>
        <th>Units</th>
        <th>Final Grade</th>
        <th>Options</th>
    </tr>

    {% for object in object_list %}
    <tr>
        <td>{{ object.semester.school_year }}</td>
        <td>{{ object.semester.semester }}</td>
        <td>{{ object.subject.subject_code }}</td>
        <td>{{ object.subject.course_title }}</td>
        <td>{{ object.subject.units }}</td>
        <td>{{ object.grade }}</td>
        <td>
            <a href="{% url 'dashboard:grade-update' object.pk %}">Edit</a>
            <a href="{% url 'dashboard:grade-delete' object.pk %}">Delete</a>
        </td>

    </tr>
    {% endfor %}

</table>
{% endblock %}